@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.advancements;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;