@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.spawner;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;