@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.world;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;