@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.concurrent;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;