@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.loot.functions;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;