@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.datasync;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;