@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.command.arguments.serializers;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;