@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.util;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;