@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.network.status;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;