@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.math.vector;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;