@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.command.impl;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;