@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.text.filter;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;