@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.state.properties;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;