@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.settings;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;