@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.inventory.container;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;