@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.pathfinding;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;