@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.loot.conditions;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;