@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.text.event;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;