@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.biome;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;