@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.registry;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;