@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.status.server;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;