@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.block.material;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;