@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.block.pattern;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;