@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.particle;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;