@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.palette;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;