@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.enchantment;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;