@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.multiplayer;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;