@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.entity.effect;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;