@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.math.shapes;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;