@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.network;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;