@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.tutorial;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;