@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.shader;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;