@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.resources;

import warcode0x.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;